### PR TITLE
Fix YML and versionCode 

### PR DESCRIPTION
**Pull request by licaon-kter**
...albeit YML would need more fixing (commit changes) after you merge :)

### CODE REVIEW

**Comment by licaon-kter** [comment]
Did you see this?

**Comment by mitchdowney** [comment]
@licaon-kter doh 🤦‍♂️ I did not. I'll make it a habit to check PRs/issues here in the future.

**Comment by licaon-kter** [comment]
Oh, I forgot to bump versioncode to 2 in YML

**Comment by mitchdowney** [comment]
Ok I can fix that 👍

**Pull request merged**
